# Generated by Django 5.0.6 on 2024-07-03 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_sub_delete_group_post_author_post_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commTitle', models.CharField(max_length=200)),
                ('commURL', models.CharField(blank=True, max_length=500, null=True)),
                ('commImg', models.ImageField(blank=True, max_length=2000, null=True, upload_to='')),
                ('commImglink', models.CharField(blank=True, max_length=500, null=True)),
                ('commDesc', models.TextField(blank=True, max_length=1000, null=True)),
                ('commDate', models.DateTimeField(blank=True, null=True)),
                ('commUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_communities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
