# Generated by Django 5.0.6 on 2024-07-03 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinComm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Joined', models.CharField(blank=True, default='FALSE', max_length=100, null=True)),
                ('JoinComm', models.ManyToManyField(related_name='forum_comms', to='forum.community')),
                ('JoinCommUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_joined_comms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
